Repository AxonFramework/extension-kotlin, pull requests merged in 2020-11, with the labels that each got.

#80 Added automatic release notes on milestone closure
  .github/release-notes.yml
  .github/workflows/release-notes.yml
Labels: Status: In Progress, Type: Enhancement

#84 Replace mailing list link with discuss.axoniq link
  .github/CONTRIBUTING.md
Labels: Priority 1: Must, Status: Resolved, Type: Bug

#73 Feature/axon kotlin test
  kotlin-test/pom.xml
  kotlin-test/src/main/kotlin/org/axonframework/extension/kotlin/test/FixtureExtensions.kt
  pom.xml
Labels: Priority 3: Could, Status: In Progress, Type: Feature
