Repository AxonFramework/extension-kotlin, pull requests merged in 2020-09, with the labels that each got.

#35 docs: add sonarcloud badge to readme, fix #34
  README.md
Labels: Priority 4: Would, Status: In Progress, Type: Enhancement

#43 Add dependabot
  .github/dependabot.yml
Labels: Priority 3: Could, Status: In Progress, Type: Feature

#33 chore: add github templates
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/1_bug_report.md
  .github/ISSUE_TEMPLATE/2_feature_request.md
Labels: Priority 4: Would, Status: In Progress, Type: Feature

#41 setup maven cache for GH Actions
  .github/workflows/maven.yml
Labels: Priority 2: Should, Status: Resolved, Type: Enhancement

#63 Fix compilation issues in tests after Kotlin 1.4 upgrade
  kotlin/src/test/kotlin/org/axonframework/extensions/kotlin/QueryGatewayExtensionsTest.kt
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#37 pom improvements
  .editorconfig
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  README.md
  kotlin/pom.xml
  mvnw
  mvnw.cmd
  pom.xml
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#39 Chore/gha trigger
  .github/workflows/maven.yml
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#36 reified both types on command gateway send
  kotlin/src/main/kotlin/org/axonframework/extensions/kotlin/CommandGatewayExtensions.kt
  kotlin/src/main/kotlin/org/axonframework/extensions/kotlin/ResultDiscriminatorCommandCallback.kt
  kotlin/src/test/kotlin/org/axonframework/extensions/kotlin/CommandGatewayExtensionsTest.kt
Labels: Priority 1: Must, Status: In Progress, Type: Feature
