Repository AxonFramework/extension-kotlin, pull requests merged in 2020-08, with the labels that each got.

#15 Maven license plugin removal
  kotlin/pom.xml
  kotlin/src/license/axon_apache_v2/header.txt
  kotlin/src/license/axon_apache_v2/license.txt
  kotlin/src/license/licenses.properties
  kotlin/src/main/kotlin/org/axonframework/extensions/kotlin/CommandGatewayExtensions.kt
  kotlin/src/main/kotlin/org/axonframework/extensions/kotlin/EventUpcaster.kt
  kotlin/src/main/kotlin/org/axonframework/extensions/kotlin/GenericEventMessageExtensions.kt
  kotlin/src/main/kotlin/org/axonframework/extensions/kotlin/QueryGatewayExtensions.kt
  pom.xml
Labels: Priority 2: Should, Status: In Progress, Type: Bug

#25 CI matrix setup and improvements
  .github/workflows/maven.yml
Labels: Priority 1: Must, Status: In Progress, Type: Feature

#23 #22 Rename Query gateway extension methods
  kotlin/src/main/kotlin/org/axonframework/extensions/kotlin/QueryGatewayExtensions.kt
  kotlin/src/test/kotlin/org/axonframework/extensions/kotlin/QueryGatewayExtensionsTest.kt
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#27 Add reified generics based extension of QueryUpdateEmitter's emit
  kotlin/src/main/kotlin/org/axonframework/extensions/kotlin/QueryUpdateEmitterExtensions.kt
  kotlin/src/test/kotlin/org/axonframework/extensions/kotlin/QueryUpdateEmitterExtensionsTest.kt
Labels: Priority 2: Should, Status: In Progress, Type: Feature

#24 Cleanup and version upgrades
  kotlin/src/main/kotlin/org/axonframework/extensions/kotlin/GenericEventMessageExtensions.kt
  kotlin/src/test/kotlin/org/axonframework/extensions/kotlin/CommandGatewayExtensionsTest.kt
  kotlin/src/test/kotlin/org/axonframework/extensions/kotlin/QueryGatewayExtensionsTest.kt
  kotlin/src/test/kotlin/org/axonframework/extensions/kotlin/ResultDiscriminatorCommandCallbackTest.kt
  kotlin/src/test/kotlin/org/axonframework/extensions/kotlin/testObjects.kt
  pom.xml
Labels: Priority 1: Must, Status: In Progress, Type: Dependency Upgrade, Type: Enhancement
